const helperGpt  = {
    "Segunda-feira": "Se hoje é segunda-feira, para a segunda-feira da próxima semana, deverá somar 7 dias com a data atual, para a terça-feira da próxima semana, deverá somar 8 dias com a data atual, para a quarta-feira da próxima semana, deverá somar 9 dias com a data atual, para a quinta-feira da próxima semana, deverá somar 10 dias com a data atual, para a sexta-feira da próxima semana, deverá somar 11 dias com a data atual, para o sábado da próxima semana, deverá somar 12 dias com a data atual, para o domingo da próxima semana, deverá somar 13 dias com a data atual.",
    "Terça-feira": "Se hoje é terça-feira, para a terça-feira da próxima semana, deverá somar 7 dias com a data atual, para a quarta-feira da próxima semana, deverá somar 8 dias com a data atual, para a quinta-feira da próxima semana, deverá somar 9 dias com a data atual, para a sexta-feira da próxima semana, deverá somar 10 dias com a data atual, para o sábado da próxima semana, deverá somar 11 dias com a data atual, para o domingo da próxima semana, deverá somar 12 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 13 dias com a data atual.",
    "Quarta-feira": "Se hoje é quarta-feira, para a quarta-feira da próxima semana, deverá somar 7 dias com a data atual, para a quinta-feira da próxima semana, deverá somar 8 dias com a data atual, para a sexta-feira da próxima semana, deverá somar 9 dias com a data atual, para o sábado da próxima semana, deverá somar 10 dias com a data atual, para o domingo da próxima semana, deverá somar 11 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 12 dias com a data atual, para a terça-feira da semana seguinte, deverá somar 13 dias com a data atual.",
    "Quinta-feira": "Se hoje é quinta-feira, para a quinta-feira da próxima semana, deverá somar 7 dias com a data atual, para a sexta-feira da próxima semana, deverá somar 8 dias com a data atual, para o sábado da próxima semana, deverá somar 9 dias com a data atual, para o domingo da próxima semana, deverá somar 10 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 11 dias com a data atual, para a terça-feira da semana seguinte, deverá somar 12 dias com a data atual, para a quarta-feira da semana seguinte, deverá somar 13 dias com a data atual.",
    "Sexta-feira": "Se hoje é sexta-feira, para a sexta-feira da próxima semana, deverá somar 7 dias com a data atual, para o sábado da próxima semana, deverá somar 8 dias com a data atual, para o domingo da próxima semana, deverá somar 9 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 10 dias com a data atual, para a terça-feira da semana seguinte, deverá somar 11 dias com a data atual, para a quarta-feira da semana seguinte, deverá somar 12 dias com a data atual, para a quinta-feira da semana seguinte, deverá somar 13 dias com a data atual.",
    "Sábado": "Se hoje é sábado, para o sábado da próxima semana, deverá somar 7 dias com a data atual, para o domingo da próxima semana, deverá somar 8 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 9 dias com a data atual, para a terça-feira da semana seguinte, deverá somar 10 dias com a data atual, para a quarta-feira da semana seguinte, deverá somar 11 dias com a data atual, para a quinta-feira da semana seguinte, deverá somar 12 dias com a data atual, para a sexta-feira da semana seguinte, deverá somar 13 dias com a data atual.",
    "Domingo": "Se hoje é domingo, para o domingo da próxima semana, deverá somar 7 dias com a data atual, para a segunda-feira da semana seguinte, deverá somar 8 dias com a data atual, para a terça-feira da semana seguinte, deverá somar 9 dias com a data atual, para a quarta-feira da semana seguinte, deverá somar 10 dias com a data atual, para a quinta-feira da semana seguinte, deverá somar 11 dias com a data atual, para a sexta-feira da semana seguinte, deverá somar 12 dias com a data atual, para o sábado da semana seguinte, deverá somar 13 dias com a data atual."
}

export default helperGpt


